# Generated by Django 4.1.11 on 2023-09-12 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('profanity', 'Profanity'), ('advertisement', 'Advertisement'), ('spam', 'Spam')], max_length=30)),
                ('report_at', models.DateTimeField(auto_now_add=True)),
                ('report_content', models.TextField()),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Report',
                'ordering': ['-report_at'],
            },
        ),
    ]
