# Generated by Django 4.1.11 on 2023-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_at'], 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('profanity', '욕설'), ('advertisement', '광고'), ('spam', '스팸 및 도배')], max_length=30),
        ),
    ]
